language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

before_install:
    - pecl install -f zmq
    - pecl install -f igbinary

install:
    - composer install

script:
    - composer analyze
    - composer test
