language: php

php:
    - '7.1'
    - '7.2'

addons:
    apt:
        packages:
            - libzmq-dev

before_install:
    - echo "yes" | pecl -d preferred_state=beta install zmq
    - pecl install -f igbinary

install:
    - composer install

script:
    - composer analyze
    - composer test
